version: "1"
services:
  nginx-react:
    image: reactapp:latest
    container_name: mms-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
