spring:
  application:
    name: MMSBackend

  datasource:
      url: jdbc:mysql://docker-mysql:3306/my_medical_secretary?createDatabaseIfNotExist=true
#      url: jdbc:mysql://localhost:3306/my_medical_secretary?createDatabaseIfNotExist=true
      username: root
      password: root
#      password: password

#      username: mmsadmin
#      password: Password123
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true

  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB

  mail:
    host: ${EMAIL_HOST}
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3_600_000
  refresh-token-expiration: 86_400_000

admin:
  defaultEmail: ${ROOT_ADMIN_EMAIL}
  default-username: ${ROOT_ADMIN_USERNAME}
  default-password: ${ROOT_ADMIN_PASSWORD}

passcode:
  passcode_length: 10
  passcode_expiry: 3_600_000

logging:
  level:
    com.example: DEBUG
