spring:
  application:
    name: MMSBackend

  datasource:
      url: jdbc:mysql://docker-mysql:3306/my_medical_secretary?createDatabaseIfNotExist=true
#      url: jdbc:mysql://localhost:3306/my_medical_secretary?createDatabaseIfNotExist=true
      username: root
      password: root
#      password: password

#      username: mmsadmin
#      password: Password123!
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true

  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB

  mail:
    host: smtp.office365.com # Depends on Clinic email
    port: 587
    username: # Get from env var!
    password: # Get from env var!
    properties:
      mail:
        protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
#  key: ${JWT_KEY}
# Create a key as an environment variable
  key: "Secret key - a_very_very_very_very_very_very_very_very_very_secret_key"
  access-token-expiration: 3_600_000
  refresh-token-expiration: 86_400_000

admin:
# Store these on the server!
  defaultEmail: "https://mymedicalsecretary.com.au/"
  default-username: "admin"
  default-password: "password"

server:
  forward-headers-strategy: framework
#  ssl:
#    key-store: classpath:springboot.p12
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: password
  port: 8080

passcode:
  passcode_length: 10
  passcode_expiry: 3_600_000

logging:
  level:
    com.example: DEBUG
