name: backendTesting
on:
  workflow_dispatch:

jobs:
  run-defined-backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend/MMSBackend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean test

